version: '3.7'
services:
    ALAS:
        network_mode: host
        volumes:
            - '.:/app/AzurLaneAutoScript:rw'
            - '/etc/localtime:/etc/localtime:ro'
        container_name: 'alas'
        image: 'alas'
        build:
            context: ./
            dockerfile: ./dev_tools/Dockerfile
