# Translations web gui
# This will insert to `config/i18n/{lang}.json`, under key `Gui`

Aside:
  Install:
  Develop:
  Performance:
  Setting:

Button:
  ScrollON:
  ScrollOFF:
  ClearLog:

Toast:
  DisableTranslateMode:
  ConfigSaved:
  AlasIsRunning:

Status:
  Running:
  Inactive:
  Warning:

MenuAlas:
  Overview:
  Log:

MenuDevelop:
  Translate:
