# --------------------
# Define non-modifiable values
# --------------------

# ==================== Maa ====================

MaaStartup:
  Scheduler:
    Enable:
      value: true
      display: disabled
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 04:00

MaaAnnihilation:
  Scheduler:
    SuccessInterval: 480
  Fight:
    Stage: Annihilation
    Medicine: 0
    Stone: 0
    Times: 5
    Drops: null
    DrGrandet: false

MaaFight:
  Scheduler:
    SuccessInterval: 480
  Fight:
    Medicine: 0
    Stone: 0
    Times: 0
    Drops: null

MaaRecruit:
  Scheduler:
    SuccessInterval: 540

MaaInfrast:
  Scheduler:
    SuccessInterval: 1200

