# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Maa ====================

Maa:
  - MaaEmulator
  - MaaRecord

MaaStartup:
  - Scheduler

MaaAnnihilation:
  - Scheduler
  - MaaFight

MaaMaterial:
  - Scheduler
  - MaaFight

MaaFight:
  - Scheduler
  - MaaFight

MaaRecruit:
  - Scheduler
  - MaaRecruit

MaaInfrast:
  - Scheduler
  - MaaInfrast

MaaVisit:
  - Scheduler

MaaMall:
  - Scheduler
  - MaaMall

MaaAward:
  - Scheduler

MaaRoguelike:
  - Scheduler
  - MaaRoguelike

# ==================== Tool ====================

MaaCopilot:
  - MaaCopilot