Alas:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Emulator:
    Serial: 127.0.0.1:5555
    PackageName: com.bilibili.azurlane
    ScreenshotMethod: ADB
    ControlMethod: minitouch
  Error:
    HandleError: true
    SaveError: true
    ScreenshotLength: 1
  DropRecord:
    SaveScreenshot: false
    SaveFolder: ./screenshot
    UploadAzurStats: false
Main:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
Commission:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: commission
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
Research:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: research
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  ResearchInput:
    UseCube: false
    UseCoin: true
    UsePart: true
  ResearchOutput:
    PresetFilter: series_4
    CustomFilter: 0.5 > reset > shortest
