Alas:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Emulator:
    Serial: 127.0.0.1:5555
    PackageName: com.bilibili.azurlane
    ScreenshotMethod: ADB
    ControlMethod: minitouch
  Error:
    HandleError: true
    SaveError: true
    ScreenshotLength: 1
  Optimization:
    CombatScreenshotInterval: 2
  DropRecord:
    SaveFolder: ./screenshots
    AzurStatsID: null
    SaveResearch: false
    UploadResearch: false
    SaveCommission: false
    UploadCommission: false
    SaveCombat: false
General:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Retirement:
    Enable: true
    RetireMode: one_click_retire
    RetireAmount: retire_all
    EnhanceFavourite: false
    EnhanceFilter: ''
    EnhanceCheckPerCategory: 2
    OldRetireN: true
    OldRetireR: true
    OldRetireSR: false
    OldRetireSSR: false
Restart:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Restart
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 00:00
Main:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Campaign:
    Name: 7-2
    Event: campaign_main
    Mode: normal
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: false
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    OilLimit: 1000
    MapAchievement: non_stop
    GetNewShip: false
    ReachLevel120: false
  Fleet:
    Fleet1: 1
    Fleet1Formation: double_line
    Fleet1Mode: combat_auto
    Fleet1Step: 3
    Fleet2: 2
    Fleet2Formation: double_line
    Fleet2Mode: combat_auto
    Fleet2Step: 2
    FleetOrder: fleet1_mob_fleet2_boss
    AutoSearchFleetOrder: fleet1_mob_fleet2_boss
  Submarine:
    Fleet: 0
    Mode: do_not_use
  Emotion:
    CalculateEmotion: true
    IgnoreLowEmotionWarn: false
    Fleet1: 119
    Fleet1RecordTime: 2020-01-01 00:00:00
    Fleet1Control: prevent_yellow_face
    Fleet1Recover: not_in_dormitory
    Fleet1Oath: false
    Fleet2: 119
    Fleet2RecordTime: 2020-01-01 00:00:00
    Fleet2Control: prevent_yellow_face
    Fleet2Recover: not_in_dormitory
    Fleet2Oath: false
  HpControl:
    UseHpBalance: false
    UseEmergencyRepair: false
    UseLowHpRetreat: false
    HpBalanceThreshold: 0.2
    HpBalanceWeight: 1000, 1000, 1000
    RepairUseSingleThreshold: 0.3
    RepairUseMultiThreshold: 0.6
    LowHpRetreatThreshold: 0.3
GemsFarming:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  GemsFarming:
    FlagshipChange: true
    FlagshipEquipChange: false
    VanguardChange: false
    VanguardEquipChange: false
    LowEmotionRetreat: true
    CommonCV: any
  Campaign:
    Name: 2-4
    Event: campaign_main
    Mode: normal
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: true
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    OilLimit: 1000
    MapAchievement: non_stop
    GetNewShip: false
    ReachLevel120: false
  Fleet:
    Fleet1: 1
    Fleet1Formation: line_ahead
    Fleet1Mode: combat_auto
    Fleet1Step: 3
    Fleet2: 2
    Fleet2Formation: line_ahead
    Fleet2Mode: combat_auto
    Fleet2Step: 2
    FleetOrder: fleet1_all_fleet2_standby
    AutoSearchFleetOrder: fleet1_all_fleet2_standby
  Submarine:
    Fleet: 0
    Mode: do_not_use
  Emotion:
    CalculateEmotion: true
    IgnoreLowEmotionWarn: false
    Fleet1: 119
    Fleet1RecordTime: 2020-01-01 00:00:00
    Fleet1Control: prevent_yellow_face
    Fleet1Recover: not_in_dormitory
    Fleet1Oath: false
    Fleet2: 119
    Fleet2RecordTime: 2020-01-01 00:00:00
    Fleet2Control: prevent_yellow_face
    Fleet2Recover: not_in_dormitory
    Fleet2Oath: false
  HpControl:
    UseHpBalance: false
    UseEmergencyRepair: false
    UseLowHpRetreat: false
    HpBalanceThreshold: 0.2
    HpBalanceWeight: 1000, 1000, 1000
    RepairUseSingleThreshold: 0.3
    RepairUseMultiThreshold: 0.6
    LowHpRetreatThreshold: 0.3
Commission:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Commission
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Commission:
    DoMajorCommission: false
    CommissionFilter: |-
      DailyEvent
      > Gem-8 > Gem-4 > Gem-2
      > Box-6 > Box-3 > Box-1
      > DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15
      > UrgentCube-3 > DailyCube-3 > UrgentCube-4 > UrgentCube-6
      > Major
      > DailyResource > DailyChip
      > UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
      > Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
      > NightOil > NightCube
      > shortest
Tactical:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Tactical
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Tactical:
    TacticalFilter: |-
      SameT3 > SameT2 > SameT1
      > BlueT2 > YellowT2 > RedT2
      > BlueT3 > YellowT3 > RedT3
      > BlueT1 > YellowT1 > RedT1
      > first
Research:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Research
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Research:
    UseCube: false
    UseCoin: true
    UsePart: true
    PresetFilter: series_4
    CustomFilter: 0.5 > reset > shortest
Dorm:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Dorm
    SuccessInterval: 278-360
    FailureInterval: 278-360
    ServerUpdate: 00:00
  Dorm:
    Collect: true
    Feed: true
    FeedFilter: 20000 > 10000 > 5000 > 3000 > 2000 > 1000
Meowfficer:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Meowfficer
    SuccessInterval: 120
    FailureInterval: 120
    ServerUpdate: 00:00
  Meowfficer:
    BuyAmount: 1
    TrainMeowfficer: false
    FortChoreMeowfficer: true
Guild:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Guild
    SuccessInterval: 40-60
    FailureInterval: 40-60
    ServerUpdate: 00:00, 12:00, 18:00, 21:00
  Logistics:
    Enable: true
    ExchangeFilter: |-
      PlateTorpedoT1 > PlateAntiAirT1 > PlatePlaneT1 > PlateGunT1 > PlateGeneralT1
      > PlateTorpedoT2 > PlateAntiAirT2 > PlatePlaneT2 > PlateGunT2 > PlateGeneralT2
      > PlateTorpedoT3 > PlateAntiAirT3 > PlatePlaneT3 > PlateGunT3 > PlateGeneralT3
      > OxyCola > Coolant > Merit > Coins > Oil
  Operation:
    Enable: true
    JoinThreshold: 1
    AttackBoss: true
    BossFleetRecommend: false
Reward:
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Reward
    SuccessInterval: 40-60
    FailureInterval: 40-60
    ServerUpdate: 00:00
  Reward:
    CollectOil: true
    CollectCoin: true
    CollectMission: true
Shop:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Shop
    SuccessInterval: 40-60
    FailureInterval: 40-60
    ServerUpdate: 00:00, 12:00, 18:00
  GeneralShop:
    UseGems: false
    Refresh: false
    Filter: |-
      BookRedT3 > BookYellowT3 > BookBlueT3 > BookRedT2
      > Cube
      > FoodT6 > FoodT5
  GuildShop:
    Refresh: true
    Filter: PlateT4 > BookT3 > PRBP > CatT3 > Chips > BookT2 > Retrofit > FoodT6 >
      FoodT5 > CatT2 > BoxT4
    BOX_T3: ironblood
    BOX_T4: ironblood
    BOOK_T2: red
    BOOK_T3: red
    RETROFIT_T2: cl
    RETROFIT_T3: cl
    PLATE_T2: general
    PLATE_T3: general
    PLATE_T4: gun
    PR1: neptune
    PR2: seattle
    PR3: champagne
  MedalShop:
    Filter: |-
      DR > PRY
      > BookRedT3 > BookYellowT3 > BookBlueT3 > BookRedT2 > BookYellowT2 > BookBlueT2
      > BulinT2 > RetrofitT3 > PlateGeneralT3
      > FoodT6 > FoodT5
  MeritShop:
    Refresh: false
    Filter: Cube
Shipyard:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Shipyard
    SuccessInterval: 120
    FailureInterval: 120
    ServerUpdate: 04:00
  Shipyard:
    ResearchSeries: 1
    ShipIndex: 0
    BuyAmount: 2
Daily:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Daily
    SuccessInterval: 120
    FailureInterval: 120
    ServerUpdate: 00:00
  Daily:
    UseDailySkip: true
    EscortMission: first
    EscortMissionFleet: 5
    AdvanceMission: first
    AdvanceMissionFleet: 5
    FierceAssault: first
    FierceAssaultFleet: 5
    TacticalTraining: second
    TacticalTrainingFleet: 5
    SupplyLineDisruption: second
Hard:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Hard
    SuccessInterval: 120
    FailureInterval: 120
    ServerUpdate: 00:00
  Hard:
    HardStage: 11-4
    HardFleet: 1
Exercise:
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Exercise
    SuccessInterval: 120
    FailureInterval: 120
    ServerUpdate: 00:00, 12:00, 18:00
  Exercise:
    OpponentChooseMode: max_exp
    OpponentTrial: 1
    ExercisePreserve: 0
    LowHpThreshold: 0.4
    LowHpConfirmWait: 0.1
  OpponentRefresh:
    Count: 0
    Record: 2020-01-01 00:00:00
