Alas:
  _info:
    Menu: Alas
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Emulator:
    Serial: 127.0.0.1:5555
    PackageName: com.bilibili.azurlane
    ScreenshotMethod:
      value: ADB
      option:
        - ADB
        - uiautomator2
        - aScreenCap
    ControlMethod:
      value: minitouch
      option:
        - ADB
        - uiautomator2
        - minitouch
  Error:
    HandleError: true
    SaveError: true
    ScreenshotLength: 1
  DropRecord:
    SaveFolder: ./screenshots
    AzurStatsID: null
    SaveResearch: false
    UploadResearch: false
    SaveCommission: false
    UploadCommission: false
    SaveCombat: false
Main:
  _info:
    Menu: Main
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
Commission:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Commission
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Commission:
    DoMajorCommission: false
    CommissionFilter: |-
      DailyEvent
      > Gem-8 > Gem-4 > Gem-2
      > Box-6 > Box-3 > Box-1
      > DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:40 > UrgentCube-2:15
      > UrgentCube-3 > DailyCube-3 > UrgentCube-4 > UrgentCube-6
      > Major
      > DailyRescource > DailyChip
      > UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
      > Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
      > NightOil > NightCube
      > shortest
Tactical:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Tactical
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Tactical:
    TacticalFilter: |-
      SameT3 > SameT2 > SameT1
      > BlueT2 > YellowT2 > RedT2
      > BlueT3 > YellowT3 > RedT3
      > BlueT1 > YellowT1 > RedT1
      > first
Research:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Research
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Research:
    UseCube: false
    UseCoin: true
    UsePart: true
    PresetFilter:
      value: series_4
      option:
        - custom
        - series_4
        - series_3
        - series_3_than_2
    CustomFilter: 0.5 > reset > shortest
