Alas:
  _info:
    Menu: Alas
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Emulator:
    Serial: 127.0.0.1:5555
    PackageName: com.bilibili.azurlane
    ScreenshotMethod:
      value: ADB
      option: ['ADB', 'uiautomator2', 'aScreenCap']
    ControlMethod:
      value: minitouch
      option: ['ADB', 'uiautomator2', 'minitouch']
  Error:
    HandleError: true
    SaveError: true
    ScreenshotLength: 1
  Optimization:
    CombatScreenshotInterval: 2
  DropRecord:
    SaveFolder: ./screenshots
    AzurStatsID: null
    SaveResearch: false
    UploadResearch: false
    SaveCommission: false
    UploadCommission: false
    SaveCombat: false
General:
  _info:
    Menu: Alas
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Retirement:
    Enable: true
    RetireMode:
      value: one_click_retire
      option: ['one_click_retire', 'enhance', 'old_retire']
    RetireAmount:
      value: retire_all
      option: ['retire_all', 'retire_10']
    EnhanceFavourite: false
    EnhanceFilter: ''
    EnhanceCheckPerCategory: 2
    OldRetireN: true
    OldRetireR: true
    OldRetireSR: false
    OldRetireSSR: false
Restart:
  _info:
    Menu: Alas
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Restart
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 00:00
Main:
  _info:
    Menu: Main
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Campaign:
    Name: 7-2
    Event: campaign_main
    Mode:
      value: normal
      option: ['normal', 'hard']
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: false
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    OilLimit: 1000
    MapAchievement:
      value: non_stop
      option: ['non_stop', '100_percent_clear', 'map_3_stars', 'threat_safe', 'threat_safe_without_3_stars']
    GetNewShip: false
    ReachLevel120: false
  Fleet:
    Fleet1:
      value: 1
      option: [1, 2, 3, 4, 5, 6]
    Fleet1Formation:
      value: double_line
      option: ['line_ahead', 'double_line', 'diamond']
    Fleet1Mode:
      value: combat_auto
      option: ['combat_auto', 'combat_manual', 'stand_still_in_the_middle', 'hide_in_bottom_left']
    Fleet1Step:
      value: 3
      option: [2, 3, 4, 5]
    Fleet2:
      value: 2
      option: [0, 1, 2, 3, 4, 5, 6]
    Fleet2Formation:
      value: double_line
      option: ['line_ahead', 'double_line', 'diamond']
    Fleet2Mode:
      value: combat_auto
      option: ['combat_auto', 'combat_manual', 'stand_still_in_the_middle', 'hide_in_bottom_left']
    Fleet2Step:
      value: 2
      option: [2, 3, 4, 5]
    FleetOrder:
      value: fleet1_mob_fleet2_boss
      option: ['fleet1_mob_fleet2_boss', 'fleet1_all_fleet2_standby']
    AutoSearchFleetOrder:
      value: fleet1_mob_fleet2_boss
      option: ['fleet1_mob_fleet2_boss', 'fleet1_boss_fleet2_mob', 'fleet1_all_fleet2_standby', 'fleet1_standby_fleet2_all']
  Submarine:
    Fleet:
      value: 0
      option: [0, 1, 2]
    Mode:
      value: do_not_use
      option: ['do_not_use','hunt_only', 'every_combat']
  Emotion:
    CalculateEmotion: true
    IgnoreLowEmotionWarn: false
    Fleet1: 119
    Fleet1RecordTime: 2020-01-01 00:00:00
    Fleet1Control:
      value: prevent_yellow_face
      option: ['keep_exp_bonus', 'prevent_green_face', 'prevent_yellow_face', 'prevent_red_face']
    Fleet1Recover:
      value: not_in_dormitory
      option: ['not_in_dormitory', 'dormitory_floor_1', 'dormitory_floor_2']
    Fleet1Oath: false
    Fleet2: 119
    Fleet2RecordTime: 2020-01-01 00:00:00
    Fleet2Control:
      value: prevent_yellow_face
      option: ['keep_exp_bonus', 'prevent_green_face', 'prevent_yellow_face', 'prevent_red_face']
    Fleet2Recover:
      value: not_in_dormitory
      option: ['not_in_dormitory', 'dormitory_floor_1', 'dormitory_floor_2']
    Fleet2Oath: false
  HpControl:
    UseHpBalance: false
    UseEmergencyRepair: false
    UseLowHpRetreat: false
    HpBalanceThreshold: 0.2
    HpBalanceWeight: 1000, 1000, 1000
    RepairUseSingleThreshold: 0.3
    RepairUseMultiThreshold: 0.6
    LowHpRetreatThreshold: 0.3
GemsFarming:
  _info:
    Menu: Main
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  GemsFarming:
    FlagshipChange: true
    FlagshipEquipChange: false
    VanguardChange: false
    VanguardEquipChange: false
    LowEmotionRetreat: true
    CommonCV:
      value: any
      option: ['any', 'langley', 'bogue', 'ranger', 'hermes']
  Campaign:
    Name: 2-4
    Event: campaign_main
    Mode:
      value: normal
      option: ['normal', 'hard']
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: true
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    OilLimit: 1000
    MapAchievement:
      value: non_stop
      option: ['non_stop', '100_percent_clear', 'map_3_stars', 'threat_safe', 'threat_safe_without_3_stars']
    GetNewShip: false
    ReachLevel120: false
  Fleet:
    Fleet1:
      value: 1
      option: [1, 2, 3, 4, 5, 6]
    Fleet1Formation:
      value: line_ahead
      option: ['line_ahead', 'double_line', 'diamond']
    Fleet1Mode:
      value: combat_auto
      option: ['combat_auto', 'combat_manual', 'stand_still_in_the_middle', 'hide_in_bottom_left']
    Fleet1Step:
      value: 3
      option: [2, 3, 4, 5]
    Fleet2:
      value: 2
      option: [0, 1, 2, 3, 4, 5, 6]
    Fleet2Formation:
      value: line_ahead
      option: ['line_ahead', 'double_line', 'diamond']
    Fleet2Mode:
      value: combat_auto
      option: ['combat_auto', 'combat_manual', 'stand_still_in_the_middle', 'hide_in_bottom_left']
    Fleet2Step:
      value: 2
      option: [2, 3, 4, 5]
    FleetOrder:
      value: fleet1_all_fleet2_standby
      option: ['fleet1_mob_fleet2_boss', 'fleet1_all_fleet2_standby']
    AutoSearchFleetOrder:
      value: fleet1_all_fleet2_standby
      option: ['fleet1_mob_fleet2_boss', 'fleet1_boss_fleet2_mob', 'fleet1_all_fleet2_standby', 'fleet1_standby_fleet2_all']
  Submarine:
    Fleet:
      value: 0
      option: [0, 1, 2]
    Mode:
      value: do_not_use
      option: ['do_not_use','hunt_only', 'every_combat']
  Emotion:
    CalculateEmotion: true
    IgnoreLowEmotionWarn: false
    Fleet1: 119
    Fleet1RecordTime: 2020-01-01 00:00:00
    Fleet1Control:
      value: prevent_yellow_face
      option: ['keep_exp_bonus', 'prevent_green_face', 'prevent_yellow_face', 'prevent_red_face']
    Fleet1Recover:
      value: not_in_dormitory
      option: ['not_in_dormitory', 'dormitory_floor_1', 'dormitory_floor_2']
    Fleet1Oath: false
    Fleet2: 119
    Fleet2RecordTime: 2020-01-01 00:00:00
    Fleet2Control:
      value: prevent_yellow_face
      option: ['keep_exp_bonus', 'prevent_green_face', 'prevent_yellow_face', 'prevent_red_face']
    Fleet2Recover:
      value: not_in_dormitory
      option: ['not_in_dormitory', 'dormitory_floor_1', 'dormitory_floor_2']
    Fleet2Oath: false
  HpControl:
    UseHpBalance: false
    UseEmergencyRepair: false
    UseLowHpRetreat: false
    HpBalanceThreshold: 0.2
    HpBalanceWeight: 1000, 1000, 1000
    RepairUseSingleThreshold: 0.3
    RepairUseMultiThreshold: 0.6
    LowHpRetreatThreshold: 0.3
Commission:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Commission
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Commission:
    DoMajorCommission: false
    CommissionFilter: |-
      DailyEvent
      > Gem-8 > Gem-4 > Gem-2
      > Box-6 > Box-3 > Box-1
      > DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15
      > UrgentCube-3 > DailyCube-3 > UrgentCube-4 > UrgentCube-6
      > Major
      > DailyResource > DailyChip
      > UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
      > Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
      > NightOil > NightCube
      > shortest
Tactical:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Tactical
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Tactical:
    TacticalFilter: |-
      SameT3 > SameT2 > SameT1
      > BlueT2 > YellowT2 > RedT2
      > BlueT3 > YellowT3 > RedT3
      > BlueT1 > YellowT1 > RedT1
      > first
Research:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Research
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  Research:
    UseCube: false
    UseCoin: true
    UsePart: true
    PresetFilter:
      value: series_4
      option:
        - custom
        - series_4
        - series_3
        - series_3_than_2
    CustomFilter: 0.5 > reset > shortest
Dorm:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Dorm
    SuccessInterval: 278-360
    FailureInterval: 278-360
    ServerUpdate: 00:00
  Dorm:
    Collect: true
    Feed: true
    FeedFilter: 20000 > 10000 > 5000 > 3000 > 2000 > 1000
Reward:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Reward
    SuccessInterval: 40-60
    FailureInterval: 40-60
    ServerUpdate: 00:00
  Reward:
    CollectOil: true
    CollectCoin: true
    CollectMission: true
