Alas:
  _info:
    Menu: Alas
  Scheduler:
    Enable: false
    NextRun: 2020-01-01 00:00:00
    Command: Alas
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
  Emulator:
    Serial: 127.0.0.1:5555
    PackageName: com.bilibili.azurlane
    ScreenshotMethod:
      value: ADB
      option:
        - ADB
        - uiautomator2
        - aScreenCap
    ControlMethod:
      value: minitouch
      option:
        - ADB
        - uiautomator2
        - minitouch
  Error:
    HandleError: true
    SaveError: true
    ScreenshotLength: 1
  DropRecord:
    SaveScreenshot: false
    SaveFolder: ./screenshot
    UploadAzurStats: false
Main:
  _info:
    Menu: Main
  Scheduler:
    Enable: main
    NextRun: 2020-01-01 00:00:00
    Command: Main
    SuccessInterval: 0
    FailureInterval: 120
    ServerUpdate: 00:00
Commission:
  _info:
    Menu: Reward
  Scheduler:
    Enable: commission
    NextRun: 2020-01-01 00:00:00
    Command: Commission
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
Research:
  _info:
    Menu: Reward
  Scheduler:
    Enable: true
    NextRun: 2020-01-01 00:00:00
    Command: Research
    SuccessInterval: 10-40
    FailureInterval: 10-40
    ServerUpdate: 00:00
  ResearchInput:
    UseCube: false
    UseCoin: true
    UsePart: true
  ResearchOutput:
    PresetFilter:
      value: series_4
      option:
        - custom
        - series_4
        - series_3
        - series_3_than_2
    CustomFilter: 0.5 > reset > shortest
