_default:
  '1':
    func: Alas
    group: _info
    arg: _info
    lang: zh-CN
    name: Alas._info._info.name
    help: Alas._info._info.help
    type: ''
    value: ''
    option: {}
  '2':
    func: Alas
    group: _info
    arg: Menu
    lang: zh-CN
    name: Alas._info.Menu.name
    help: Alas._info.Menu.help
    type: input
    value: Alas
    option: {}
  '3':
    func: Alas
    group: Scheduler
    arg: _info
    lang: zh-CN
    name: Alas.Scheduler._info.name
    help: Alas.Scheduler._info.help
    type: ''
    value: ''
    option: {}
  '4':
    func: Alas
    group: Scheduler
    arg: Enable
    lang: zh-CN
    name: Alas.Scheduler.Enable.name
    help: Alas.Scheduler.Enable.help
    type: input
    value: false
    option: {}
  '5':
    func: Alas
    group: Scheduler
    arg: NextRun
    lang: zh-CN
    name: Alas.Scheduler.NextRun.name
    help: Alas.Scheduler.NextRun.help
    type: input
    value: 2020-01-01 00:00:00
    option: {}
  '6':
    func: Alas
    group: Scheduler
    arg: Command
    lang: zh-CN
    name: Alas.Scheduler.Command.name
    help: Alas.Scheduler.Command.help
    type: input
    value: Alas
    option: {}
  '7':
    func: Alas
    group: Scheduler
    arg: SuccessInterval
    lang: zh-CN
    name: Alas.Scheduler.SuccessInterval.name
    help: Alas.Scheduler.SuccessInterval.help
    type: input
    value: 0
    option: {}
  '8':
    func: Alas
    group: Scheduler
    arg: FailureInterval
    lang: zh-CN
    name: Alas.Scheduler.FailureInterval.name
    help: Alas.Scheduler.FailureInterval.help
    type: input
    value: 120
    option: {}
  '9':
    func: Alas
    group: Scheduler
    arg: ServerUpdate
    lang: zh-CN
    name: Alas.Scheduler.ServerUpdate.name
    help: Alas.Scheduler.ServerUpdate.help
    type: input
    value: 00:00
    option: {}
  '10':
    func: Alas
    group: Emulator
    arg: _info
    lang: zh-CN
    name: Alas.Emulator._info.name
    help: Alas.Emulator._info.help
    type: ''
    value: ''
    option: {}
  '11':
    func: Alas
    group: Emulator
    arg: Serial
    lang: zh-CN
    name: Alas.Emulator.Serial.name
    help: Alas.Emulator.Serial.help
    type: input
    value: 127.0.0.1:5555
    option: {}
  '12':
    func: Alas
    group: Emulator
    arg: PackageName
    lang: zh-CN
    name: Alas.Emulator.PackageName.name
    help: Alas.Emulator.PackageName.help
    type: input
    value: com.bilibili.azurlane
    option: {}
  '13':
    func: Alas
    group: Emulator
    arg: ScreenshotMethod
    lang: zh-CN
    name: Alas.Emulator.ScreenshotMethod.name
    help: Alas.Emulator.ScreenshotMethod.help
    type: input
    value: ADB
    option:
      ADB: ADB
      uiautomator2: uiautomator2
      aScreenCap: aScreenCap
  '14':
    func: Alas
    group: Emulator
    arg: ControlMethod
    lang: zh-CN
    name: Alas.Emulator.ControlMethod.name
    help: Alas.Emulator.ControlMethod.help
    type: input
    value: minitouch
    option:
      ADB: ADB
      uiautomator2: uiautomator2
      minitouch: minitouch
  '15':
    func: Alas
    group: Error
    arg: _info
    lang: zh-CN
    name: Alas.Error._info.name
    help: Alas.Error._info.help
    type: ''
    value: ''
    option: {}
  '16':
    func: Alas
    group: Error
    arg: HandleError
    lang: zh-CN
    name: Alas.Error.HandleError.name
    help: Alas.Error.HandleError.help
    type: input
    value: true
    option: {}
  '17':
    func: Alas
    group: Error
    arg: SaveError
    lang: zh-CN
    name: Alas.Error.SaveError.name
    help: Alas.Error.SaveError.help
    type: input
    value: true
    option: {}
  '18':
    func: Alas
    group: Error
    arg: ScreenshotLength
    lang: zh-CN
    name: Alas.Error.ScreenshotLength.name
    help: Alas.Error.ScreenshotLength.help
    type: input
    value: 1
    option: {}
  '19':
    func: Alas
    group: DropRecord
    arg: _info
    lang: zh-CN
    name: Alas.DropRecord._info.name
    help: Alas.DropRecord._info.help
    type: ''
    value: ''
    option: {}
  '20':
    func: Alas
    group: DropRecord
    arg: SaveFolder
    lang: zh-CN
    name: Alas.DropRecord.SaveFolder.name
    help: Alas.DropRecord.SaveFolder.help
    type: input
    value: ./screenshot
    option: {}
  '21':
    func: Alas
    group: DropRecord
    arg: AzurStatsID
    lang: zh-CN
    name: Alas.DropRecord.AzurStatsID.name
    help: Alas.DropRecord.AzurStatsID.help
    type: input
    value: null
    option: {}
  '22':
    func: Alas
    group: DropRecord
    arg: SaveResearch
    lang: zh-CN
    name: Alas.DropRecord.SaveResearch.name
    help: Alas.DropRecord.SaveResearch.help
    type: input
    value: false
    option: {}
  '23':
    func: Alas
    group: DropRecord
    arg: UploadResearch
    lang: zh-CN
    name: Alas.DropRecord.UploadResearch.name
    help: Alas.DropRecord.UploadResearch.help
    type: input
    value: false
    option: {}
  '24':
    func: Alas
    group: DropRecord
    arg: SaveCommission
    lang: zh-CN
    name: Alas.DropRecord.SaveCommission.name
    help: Alas.DropRecord.SaveCommission.help
    type: input
    value: false
    option: {}
  '25':
    func: Alas
    group: DropRecord
    arg: UploadCommission
    lang: zh-CN
    name: Alas.DropRecord.UploadCommission.name
    help: Alas.DropRecord.UploadCommission.help
    type: input
    value: false
    option: {}
  '26':
    func: Alas
    group: DropRecord
    arg: SaveCombat
    lang: zh-CN
    name: Alas.DropRecord.SaveCombat.name
    help: Alas.DropRecord.SaveCombat.help
    type: input
    value: false
    option: {}
  '27':
    func: Main
    group: _info
    arg: _info
    lang: zh-CN
    name: Main._info._info.name
    help: Main._info._info.help
    type: ''
    value: ''
    option: {}
  '28':
    func: Main
    group: _info
    arg: Menu
    lang: zh-CN
    name: Main._info.Menu.name
    help: Main._info.Menu.help
    type: input
    value: Main
    option: {}
  '29':
    func: Main
    group: Scheduler
    arg: _info
    lang: zh-CN
    name: Main.Scheduler._info.name
    help: Main.Scheduler._info.help
    type: ''
    value: ''
    option: {}
  '30':
    func: Main
    group: Scheduler
    arg: Enable
    lang: zh-CN
    name: Main.Scheduler.Enable.name
    help: Main.Scheduler.Enable.help
    type: input
    value: main
    option: {}
  '31':
    func: Main
    group: Scheduler
    arg: NextRun
    lang: zh-CN
    name: Main.Scheduler.NextRun.name
    help: Main.Scheduler.NextRun.help
    type: input
    value: 2020-01-01 00:00:00
    option: {}
  '32':
    func: Main
    group: Scheduler
    arg: Command
    lang: zh-CN
    name: Main.Scheduler.Command.name
    help: Main.Scheduler.Command.help
    type: input
    value: Main
    option: {}
  '33':
    func: Main
    group: Scheduler
    arg: SuccessInterval
    lang: zh-CN
    name: Main.Scheduler.SuccessInterval.name
    help: Main.Scheduler.SuccessInterval.help
    type: input
    value: 0
    option: {}
  '34':
    func: Main
    group: Scheduler
    arg: FailureInterval
    lang: zh-CN
    name: Main.Scheduler.FailureInterval.name
    help: Main.Scheduler.FailureInterval.help
    type: input
    value: 120
    option: {}
  '35':
    func: Main
    group: Scheduler
    arg: ServerUpdate
    lang: zh-CN
    name: Main.Scheduler.ServerUpdate.name
    help: Main.Scheduler.ServerUpdate.help
    type: input
    value: 00:00
    option: {}
  '36':
    func: Commission
    group: _info
    arg: _info
    lang: zh-CN
    name: Commission._info._info.name
    help: Commission._info._info.help
    type: ''
    value: ''
    option: {}
  '37':
    func: Commission
    group: _info
    arg: Menu
    lang: zh-CN
    name: Commission._info.Menu.name
    help: Commission._info.Menu.help
    type: input
    value: Reward
    option: {}
  '38':
    func: Commission
    group: Scheduler
    arg: _info
    lang: zh-CN
    name: Commission.Scheduler._info.name
    help: Commission.Scheduler._info.help
    type: ''
    value: ''
    option: {}
  '39':
    func: Commission
    group: Scheduler
    arg: Enable
    lang: zh-CN
    name: Commission.Scheduler.Enable.name
    help: Commission.Scheduler.Enable.help
    type: input
    value: commission
    option: {}
  '40':
    func: Commission
    group: Scheduler
    arg: NextRun
    lang: zh-CN
    name: Commission.Scheduler.NextRun.name
    help: Commission.Scheduler.NextRun.help
    type: input
    value: 2020-01-01 00:00:00
    option: {}
  '41':
    func: Commission
    group: Scheduler
    arg: Command
    lang: zh-CN
    name: Commission.Scheduler.Command.name
    help: Commission.Scheduler.Command.help
    type: input
    value: Commission
    option: {}
  '42':
    func: Commission
    group: Scheduler
    arg: SuccessInterval
    lang: zh-CN
    name: Commission.Scheduler.SuccessInterval.name
    help: Commission.Scheduler.SuccessInterval.help
    type: input
    value: 10-40
    option: {}
  '43':
    func: Commission
    group: Scheduler
    arg: FailureInterval
    lang: zh-CN
    name: Commission.Scheduler.FailureInterval.name
    help: Commission.Scheduler.FailureInterval.help
    type: input
    value: 10-40
    option: {}
  '44':
    func: Commission
    group: Scheduler
    arg: ServerUpdate
    lang: zh-CN
    name: Commission.Scheduler.ServerUpdate.name
    help: Commission.Scheduler.ServerUpdate.help
    type: input
    value: 00:00
    option: {}
  '45':
    func: Research
    group: _info
    arg: _info
    lang: zh-CN
    name: Research._info._info.name
    help: Research._info._info.help
    type: ''
    value: ''
    option: {}
  '46':
    func: Research
    group: _info
    arg: Menu
    lang: zh-CN
    name: Research._info.Menu.name
    help: Research._info.Menu.help
    type: input
    value: Reward
    option: {}
  '47':
    func: Research
    group: Scheduler
    arg: _info
    lang: zh-CN
    name: Research.Scheduler._info.name
    help: Research.Scheduler._info.help
    type: ''
    value: ''
    option: {}
  '48':
    func: Research
    group: Scheduler
    arg: Enable
    lang: zh-CN
    name: Research.Scheduler.Enable.name
    help: Research.Scheduler.Enable.help
    type: input
    value: true
    option: {}
  '49':
    func: Research
    group: Scheduler
    arg: NextRun
    lang: zh-CN
    name: Research.Scheduler.NextRun.name
    help: Research.Scheduler.NextRun.help
    type: input
    value: 2020-01-01 00:00:00
    option: {}
  '50':
    func: Research
    group: Scheduler
    arg: Command
    lang: zh-CN
    name: Research.Scheduler.Command.name
    help: Research.Scheduler.Command.help
    type: input
    value: Research
    option: {}
  '51':
    func: Research
    group: Scheduler
    arg: SuccessInterval
    lang: zh-CN
    name: Research.Scheduler.SuccessInterval.name
    help: Research.Scheduler.SuccessInterval.help
    type: input
    value: 10-40
    option: {}
  '52':
    func: Research
    group: Scheduler
    arg: FailureInterval
    lang: zh-CN
    name: Research.Scheduler.FailureInterval.name
    help: Research.Scheduler.FailureInterval.help
    type: input
    value: 10-40
    option: {}
  '53':
    func: Research
    group: Scheduler
    arg: ServerUpdate
    lang: zh-CN
    name: Research.Scheduler.ServerUpdate.name
    help: Research.Scheduler.ServerUpdate.help
    type: input
    value: 00:00
    option: {}
  '54':
    func: Research
    group: ResearchInput
    arg: _info
    lang: zh-CN
    name: Research.ResearchInput._info.name
    help: Research.ResearchInput._info.help
    type: ''
    value: ''
    option: {}
  '55':
    func: Research
    group: ResearchInput
    arg: UseCube
    lang: zh-CN
    name: Research.ResearchInput.UseCube.name
    help: Research.ResearchInput.UseCube.help
    type: input
    value: false
    option: {}
  '56':
    func: Research
    group: ResearchInput
    arg: UseCoin
    lang: zh-CN
    name: Research.ResearchInput.UseCoin.name
    help: Research.ResearchInput.UseCoin.help
    type: input
    value: true
    option: {}
  '57':
    func: Research
    group: ResearchInput
    arg: UsePart
    lang: zh-CN
    name: Research.ResearchInput.UsePart.name
    help: Research.ResearchInput.UsePart.help
    type: input
    value: true
    option: {}
  '58':
    func: Research
    group: ResearchOutput
    arg: _info
    lang: zh-CN
    name: Research.ResearchOutput._info.name
    help: Research.ResearchOutput._info.help
    type: ''
    value: ''
    option: {}
  '59':
    func: Research
    group: ResearchOutput
    arg: PresetFilter
    lang: zh-CN
    name: Research.ResearchOutput.PresetFilter.name
    help: Research.ResearchOutput.PresetFilter.help
    type: input
    value: series_4
    option:
      custom: custom
      series_4: series_4
      series_3: series_3
      series_3_than_2: series_3_than_2
  '60':
    func: Research
    group: ResearchOutput
    arg: CustomFilter
    lang: zh-CN
    name: Research.ResearchOutput.CustomFilter.name
    help: Research.ResearchOutput.CustomFilter.help
    type: input
    value: 0.5 > reset > shortest
    option: {}
